- extension.js
Changes radio station to the next or previous one on the channels list.
> Support for Next/Prev media keys

- CHANGELOG.md
- README.md
Hi,
Just a few typo spotted by check-all-the-things. :)
> Fix a few typo

- radio@hslbck.gmail.com/addChannelDialog.js
- radio@hslbck.gmail.com/channel.js
- radio@hslbck.gmail.com/channelListDialog.js
- radio@hslbck.gmail.com/extension.js
- radio@hslbck.gmail.com/io.js
- radio@hslbck.gmail.com/player.js
- radio@hslbck.gmail.com/po/bg.po
- radio@hslbck.gmail.com/po/da.po
- radio@hslbck.gmail.com/po/de.po
- radio@hslbck.gmail.com/po/fr.po
- radio@hslbck.gmail.com/po/hu.po
- radio@hslbck.gmail.com/po/pl.po
- radio@hslbck.gmail.com/po/ru.po
- radio@hslbck.gmail.com/po/tr.po
- radio@hslbck.gmail.com/po/zh_CN.po
- radio@hslbck.gmail.com/prefs.js
- radio@hslbck.gmail.com/searchDialog.js
Hi,
I added copyright in `.po` files and `.js` files and also updated `.po` files.
Maybe it would be a good idea to ask contributors to run `make build` after they did any change to the code before sending a PR, so that, `.po` files would be updated in the same time (would produce a cleaner git history) ?
> Add copyright informations and update po files

- Makefile
- README.md
Hi,
Looking at the commits would be faster than reading me to understand the changes. :)
> Minor updates on Makefile and README

- radio@hslbck.gmail.com/convertCharset.js
Hi,
Add the Expat (MIT) license to `convertCharset.js` and add copyright holders.
> Add license and copyright holders for convertCharset.js

- CONTRIBUTING.md
- README.md
Hi,
I removed duplicated information and cleaned a few things.
> Clean README

- CONTRIBUTING.md
- README.md
> More README cleaning

- CHANGELOG.md
- radio@hslbck.gmail.com/player.js
- radio@hslbck.gmail.com/po/bg.po
- radio@hslbck.gmail.com/po/da.po
- radio@hslbck.gmail.com/po/de.po
- radio@hslbck.gmail.com/po/es.po
- radio@hslbck.gmail.com/po/fr.po
- radio@hslbck.gmail.com/po/hu.po
- radio@hslbck.gmail.com/po/pl.po
- radio@hslbck.gmail.com/po/pt.po
- radio@hslbck.gmail.com/po/ru.po
- radio@hslbck.gmail.com/po/tr.po
- radio@hslbck.gmail.com/po/zh_CN.po
- radio@hslbck.gmail.com/prefs.js
- radio@hslbck.gmail.com/radioMenu.js
- radio@hslbck.gmail.com/schemas/org.gnome.shell.extensions.radio.gschema.xml
A volume slider with option to toggle it in the settings.
> Volume slider

- CHANGELOG.md
- radio@hslbck.gmail.com/po/bg.po
- radio@hslbck.gmail.com/po/da.po
- radio@hslbck.gmail.com/po/de.po
- radio@hslbck.gmail.com/po/es.po
- radio@hslbck.gmail.com/po/fr.po
- radio@hslbck.gmail.com/po/hu.po
- radio@hslbck.gmail.com/po/pl.po
- radio@hslbck.gmail.com/po/pt.po
- radio@hslbck.gmail.com/po/pt_BR.po
- radio@hslbck.gmail.com/po/ru.po
- radio@hslbck.gmail.com/po/tr.po
- radio@hslbck.gmail.com/po/zh_CN.po
Hi,
I updated the french translation (and the .po files in the same time).
> Update .po files and french translation

- CHANGELOG.md
- radio@hslbck.gmail.com/po/da.po
> Update danish translation

- CHANGELOG.md
- radio@hslbck.gmail.com/player.js
- radio@hslbck.gmail.com/po/bg.po
- radio@hslbck.gmail.com/po/da.po
- radio@hslbck.gmail.com/po/de.po
- radio@hslbck.gmail.com/po/es.po
- radio@hslbck.gmail.com/po/fr.po
- radio@hslbck.gmail.com/po/hu.po
- radio@hslbck.gmail.com/po/pl.po
- radio@hslbck.gmail.com/po/pt.po
- radio@hslbck.gmail.com/po/pt_BR.po
- radio@hslbck.gmail.com/po/ru.po
- radio@hslbck.gmail.com/po/tr.po
- radio@hslbck.gmail.com/po/zh_CN.po
Hi,
Fix #81.
I removed the hard-coded strings, updated the `.po` files and updated the french translation.
Should not be merged yet, because #80 should be merged first and I've got a few things to fix.
> Remove hardcoded strings

- radio@hslbck.gmail.com/po/it.po
> Add copyright for italian translation

- radio@hslbck.gmail.com/searchDialog.js
- radio@hslbck.gmail.com/stylesheet.css
removed the close command. i tried to add a popup message to give the user some feed back but couldn't figure it out. so feel free to add that or tell me how :)
also reformatted the stylesheet since it had a different style for each block, lol.
> 91 search dialog ux

- CHANGELOG.md
- radio@hslbck.gmail.com/po/uk.po
This PR brings complete Ukrainian translation.
Cheers!
> Add Ukrainian translation

- radio@hslbck.gmail.com/addChannelDialog.js
- radio@hslbck.gmail.com/channel.js
- radio@hslbck.gmail.com/channelCreator.js
- radio@hslbck.gmail.com/player.js
- radio@hslbck.gmail.com/radioMenu.js
- radio@hslbck.gmail.com/searchDialog.js
Hi,
Some minor refactoring. I'm not really into JavaScript, so there's one thing I'm not sure about, see my review.
> Minor refactoring

- radio@hslbck.gmail.com/po/bg.po
- radio@hslbck.gmail.com/po/da.po
- radio@hslbck.gmail.com/po/de.po
- radio@hslbck.gmail.com/po/es.po
- radio@hslbck.gmail.com/po/fr.po
- radio@hslbck.gmail.com/po/hu.po
- radio@hslbck.gmail.com/po/it.po
- radio@hslbck.gmail.com/po/pl.po
- radio@hslbck.gmail.com/po/pt.po
- radio@hslbck.gmail.com/po/pt_BR.po
- radio@hslbck.gmail.com/po/ru.po
- radio@hslbck.gmail.com/po/tr.po
- radio@hslbck.gmail.com/po/uk.po
- radio@hslbck.gmail.com/po/zh_CN.po
Hi,
I updated the french translation and fixed some warnings.
> Update french translation, fix some po files

- radio@hslbck.gmail.com/convertCharset.js
Hi,
Just removed a useless `break`. :)
> Remove unreachable code

- radio@hslbck.gmail.com/channelList.json
Hi
egoFM and egoFM Riff resources were not running, New source added from original site
> egoFM and egoFM Riff updated

- radio@hslbck.gmail.com/radioMenu.js
This appears to fix hslbck/gnome-shell-extension-radio#132 . Further testing is appreciated.
> fix volume slider for gnome 3.34 v1

- radio@hslbck.gmail.com/titleMenu.js
This fixes following deprecation warnings when toggling "Show title notifications in the panel" setting.
````
Mar 16 13:06:01 sabretooth gnome-shell[1253]: Usage of object.actor is deprecated for TitleMenuButton
get@resource:///org/gnome/shell/ui/environment.js:285:29
_init@/home/junaru/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/titleMenu.js:24:9
addToPanel@/home/junaru/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/titleMenu.js:44:17
_init/<@/home/junaru/.local/share/gnome-shell/extensions/radio@hslbck.gmail.com/radioMenu.js:206:27
Mar 16 13:06:01 sabretooth gnome-shell[1253]: Usage of object.actor is deprecated for TitleMenuButton
get@resource:///org/gnome/shell/ui/environment.js:285:29
_init@/home/junaru/.local/share/gnome-shell/extensions/radio@hslbck.gmail. …
```
> Fix actor deprication warning 

- radio@hslbck.gmail.com/player.js
- radio@hslbck.gmail.com/radioMenu.js
Add artist metadata if available in the notification and in the tray.
> Display artist metadata

- radio@hslbck.gmail.com/addChannelDialog.js
- radio@hslbck.gmail.com/channelCreator.js
- radio@hslbck.gmail.com/channelListDialog.js
- radio@hslbck.gmail.com/radioMenu.js
Fixed:
* Tweener import.
* Actor issues .
Remaining issues:
* Search provider must be disabled (looks like GNOME issue).
* The settings/channels/add/search icon styling looks wrong (not sure if theme issue).
Should partially solve #157
> Initial GNOME 3.38 fixes

- radio@hslbck.gmail.com/po/hu.po
I have completed the missing strings. Upon acceptance, please tag the PR as hacktoberfest-accepted
> Update Hungarian translation

- radio@hslbck.gmail.com/channelListDialog.js
- radio@hslbck.gmail.com/metadata.json
- radio@hslbck.gmail.com/prefs.js
- radio@hslbck.gmail.com/searchDialog.js
Bumped shell version to support **GNOME 40 ONLY**, fixed preferences dialog. Fixes #172
> Gnome 40 support
